apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: djangosite-argo-application
  # namespace: default
spec:
  project: default

  source:
    repoUrl: https://github.com/IsNoble/Test-Pipeline-GCP
    targetRevision: HEAD
    path: charts
  destination: 
    server: https://kubernetes.default.svc
    namespace: djangosite

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    