apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: djangosite-argo-application
  namespace: default
spec:
  project: default
  source:
    chart: django-site
    repoURL: https://github.com/IsNoble/Test-Pipeline-GCP
    targetRevision: HEAD
    helm:
      releaseName: django-site
  destination: 
    server: https://kubernetes.default.svc
    namespace: djangosite

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    