# [START kubernetes_deployment]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tpgcpdjangoapp-dep
  labels:
    app: tpgcpdjangoapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tpgcpdjangoapp
  template:
    metadata:
      labels:
        app: tpgcpdjangoapp
    spec:
      containers:
      - name: tpgcpdjangoapp
        # Replace  with your project ID or use `make template`
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{.Values.image.imagePullPolicy}}
        ports:
        - containerPort: 8000      
# [END kubernetes_deployment]

---

